### ISSUE TITLE
[FEAT] Implement Video Storage

### ISSUE THREAD

**Issue by alin484** [SOFTENG310-Team4/SMARTJ#48]
## Summary

Enable users to save recorded video responses to their accounts for future review.

## Motivation

Storing video responses allows users to monitor their interview practice over time and compare older responses with new ones to observe improvements.

## Detailed Description

- Add functionality to save video recordings to each user’s profile.
- Allow users to access saved videos under their profiles for review purposes.
- Implement storage management to ensure videos are efficiently stored and can be retrieved.

## Possible Alternatives

Allow local storage on the user’s device if server storage is too costly or complex to maintain.

## Additional Context

Saving videos can help users with self-reflection and allow them to rewatch their responses for learning purposes.

## Implementation

- Develop storage functionality for saving video files.
- Implement efficient compression and storage techniques.
- Add UI elements in the profile section for users to manage and access their saved videos.

**Comment by axu732** [comment]
An idea currently is to use the current MongoDB database integration and store the video files via GridFS / Base64 encoding.
