### ISSUE TITLE
[FEAT] Implement Feedback System

### ISSUE THREAD

**Issue by alin484** [SOFTENG310-Team4/SMARTJ#49]
## Summary

Add a system where users can leave self-feedback on their responses and view feedback for each interview question.

## Motivation

A feedback system enhances self-assessment by letting users reflect on their answers, improving self-awareness. Viewing past feedback can also assist in tracking improvement.

## Detailed Description

- Self-Reflection Tool: Let users leave personal feedback after watching their video replays, including written notes and Likert scale ratings.
- Feedback Review: Display feedback left for each interview question and allow users to revisit it.
- Performance Sorting: Let users sort their interview responses based on self-assigned ratings.

## Possible Alternatives

Introduce automated feedback based on AI analysis of the user's response, providing objective insights.

## Additional Context

This feature will encourage users to engage more deeply with their responses, aiding in self-improvement.

## Implementation

- Implement a UI for users to leave notes and ratings after viewing a video response.
- Store feedback in the user profile, linked to the specific question or session.
- Develop sorting functionality to organize responses based on feedback ratings.

**Comment by axu732** [comment]
![image](https://github.com/user-attachments/assets/232cbeb1-58b0-4267-b2fb-9a5e6171b6cb)

Current user schema for analytics. Stored as an array that will contain sessions.

**Comment by axu732** [comment]
For text, use ChatGPT and query an API asking how well the user has answered the question based on the answer provided by the user.

**Comment by quaidsage** [comment]
Self assessment for video and automatic assessment for text has already been implemented, thus this issue can be closed.
