### ISSUE TITLE
[DOCUMENT] Add Issue Template Documentation

### ISSUE THREAD

**Issue by SOFTENG310-Team4** [SOFTENG310-Team4/SMARTJ#5]
## Summary

Add documentation for issue templates, including a feature request template, a bug report template, and a documentation template. This will provide guidance on how to use and customize these templates effectively.

## Motivation

The addition of this documentation will help users understand how to use and modify issue templates for better organization and clarity when reporting bugs, requesting features, or contributing to documentation. It addresses the need for clear guidelines on template usage, ensuring consistency and completeness in issue reporting.

## Current Documentation

Currently, there is no comprehensive documentation available for issue templates. Users may be unsure about how to use the existing templates or how to create their own.

## Proposed Changes

1. Feature Request Template Documentation:
Describe the purpose of the feature request template.
Provide an example of how to fill out the template.
Include guidelines on what information should be included to make the request clear and actionable.

2. Bug Report Template Documentation:
Explain the importance of using the bug report template for efficient issue resolution.
Provide an example of a filled-out bug report.
Offer tips on detailing the issue to facilitate debugging.

3. Documentation Template Documentation:
Outline the purpose of the documentation template.
Provide a filled-out example to illustrate how to document a feature or fix.
Include recommendations for maintaining up-to-date documentation.

## Additional Context

N/A

## Resources

N/A

**Comment by tyin363** [comment]
Added Issue Template Documentation in .github/ISSUE_TEMPLATE
