### ISSUE TITLE
[DOCUMENT] Add Initial Tasks Documentation

### ISSUE THREAD

**Issue by SOFTENG310-Team4** [SOFTENG310-Team4/SMARTJ#6]
## Summary

Add documentation for the initial tasks by listing and describing each task. This will provide a clear overview of the tasks that need to be completed and ensure that each task is well-defined and understood.

## Motivation

Providing detailed documentation of initial tasks will help team members understand what needs to be done from the outset. It ensures that all tasks are clearly defined, reducing confusion and improving task allocation and tracking.

## Current Documentation

Currently, there is no dedicated documentation for the initial tasks. Users may need to refer to scattered notes or incomplete task descriptions.

## Proposed Changes

1. List of Initial Tasks:
Create a comprehensive list of all initial tasks that need to be completed.
Include a brief description of each task to clarify its objectives.

2. Task Descriptions:
Provide detailed descriptions for each task, including any specific requirements or constraints.
Explain the expected outcome or deliverables for each task.

3. Task Categorization:
Group tasks into categories if applicable (e.g., development, testing, documentation).
Include information on any dependencies between tasks.

4. Task Assignment:
If relevant, note who is responsible for each task or how tasks should be assigned.

## Additional Context

N/A

## Resources

N/A

**Comment by tyin363** [comment]
Added documentation of initial tasks via Issues
