### ISSUE TITLE
[DOCUMENT] Update Project Documentation for Release A1

### ISSUE THREAD

**Issue by syoo881** [SOFTENG310-Team4/SMARTJ#65]
## Summary
Update and refine the project documentation to reflect the current state of the SMARTJ project after the completion of Release A1. This includes updating the README, CONTRIBUTING guidelines, and other relevant documentation, including the wiki.

## Motivation
As we've completed Release A1, our project has evolved, and our documentation needs to accurately reflect these changes. Up-to-date documentation is crucial for:
- Onboarding new contributors
- Ensuring current team members have accurate information
- Presenting our project accurately to potential users and collaborators

## Current Documentation
Our current documentation, may contain minor issues, that needs to be touched up on.

## Proposed Changes
1. Review and update all other documentation:
   - Ensure consistency across all documents
   - Remove any outdated information
   - Add new sections as needed to cover all aspects of the current project state

## Additional Context
- Read through all documentations to ensure consistency.

## Resources
- Current project [README](https://github.com/SOFTENG310-Team4/SMARTJ/blob/main/README.md)
- Current [CONTRIBUTING](https://github.com/SOFTENG310-Team4/SMARTJ/blob/main/CONTRIBUTING.md) guidelines: 
- Current [Wiki](https://github.com/SOFTENG310-Team4/SMARTJ/wiki)

**Comment by today0-o** [comment]
Completed the task of updating and refining the project documentation after Release A1. This includes reviewing and revising the README, CONTRIBUTING guidelines, and wiki for consistency and accuracy. All outdated information has been removed, and new sections have been added to reflect the current state of the project.
