### ISSUE TITLE
[REFACTOR] Modularize CSS and JavaScript Files for Improved Maintainability

### ISSUE THREAD

**Issue by syoo881** [SOFTENG310-Team4/SMARTJ#67]
## Summary
Refactor the current codebase by modularizing CSS and JavaScript files to improve maintainability, scalability, and code organization.

## Motivation
As the project has grown, and will continue to grow, the CSS and JavaScript structures have become challenging to manage. Modularizing our codebase will:
- Improve code organization and readability
- Enhance maintainability by separating concerns
- Facilitate easier updates and additions to specific components or features
- Make the codebase more scalable for future development

## Current State
- CSS: No dedicated CSS package section
- JavaScript: There are dedicated pages and components sections, but outlier js classes are not well organized.

## Proposed Changes
1. Analyze current CSS and JavaScript structure
2. Create a new directory structure for modular files:
   - CSS: e.g., /styles/components/, /styles/layouts/, /styles/globals/
   - JavaScript: e.g., /js/components/, /js/utils/, /js/services/
3. Refactor existing code into smaller, more focused files:
   - CSS: Component-specific stylesheets
   - JavaScript: Modular functions, classes, or components

## Additional Context
- This refactoring should not change the visual appearance or functionality of the application
- Consider progressive enhancement: start with small refactoring, and 
- This task may require updates to the build process to handle the new file structure

## Resources
- [CSS Modules documentation](https://github.com/css-modules/css-modules)
- [JavaScript Modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)

## Potential Challenges
- Ensuring consistent naming conventions across the team
- Managing dependencies between modules
- Balancing between over-modularization and maintainable code chunks

## Notes
- Feel free to adjust this plan based on their analysis of the codebase and any evolving project requirements.
- Documentation should be updated as required, to reflect the changes.

**Comment by quaidsage** [comment]
This was resolved in most recent pull request #93.
