### ISSUE TITLE
[FEAT] Implement Saving of Interview Practice Session

### ISSUE THREAD

**Issue by quaidsage** [SOFTENG310-Team4/SMARTJ#75]
## Summary
Add a connection between the users and their completed interview practice session. 

## Motivation
A system that saves the previous attempts of answering interview practice questions allows users to reflect on past attempts. This helps to track a users improvement over time.

## Detailed Description
* Let users review their past session attempts, including questions, answers, and generated grade. 
* Let users filter and sort past sessions based on attributes such as date, grade, or interview session type.
* Add video player for viewing of past answers done using video answer format. 

## Possible Alternatives
* Allow users to save their answers in file format.
   * This could be packaged as a zip containing the question set and the media type used to answer the questions.

## Additional Context
Adding this reviewing process for users helps to improve the functionality of the project.

## Implementation
* Save the session details under the users profile in the database for storage.
* Display the past sessions in a list when profile is viewed.
* Update the performance chart to show change in performance based on letter grades given in previous sessions.

**Comment by axu732** [comment]
Currently only works with text.

**Comment by quaidsage** [comment]
This issue has been resolved for both text and video.
